### ISSUE TITLE
Problem editing toolbox

### ISSUE THREAD

**Issue by atlarep** [arsava/dokuwiki-template-vector#53]
Navigation Box not showing all the items for certain folders.
Is there a limit as to how many items can be shown on the navigation panel?
There are a few pages missing and I am able to open them via URL, but they don't show in the Navigation panel.

**Comment by rrandall117** [comment]
How many entries do you "appear" to be limited to?

I have a family genealogy site with 85 entries in my Navigation box (running 2016-06-26a "Elenor of Tsort", Vector, and the navi plugin - last updated 2015-02-26). The navigation panel has functioned properly on past versions of Dokuwiki.

IF you have fewer navigation entries than I do... I'd point to the obvious. Make sure that you've used the proper syntax for those entries that do not appear in your Navigation panel (this is where I find most of my problems).

Next, I'd update ALL of the plugins (even though they may appear un-related).

Finally, because I've encountered past plugin conflicts that no one else has experienced (on a completely different Dokuwiki site), If no one else is seeing the same problem you're experiencing, then I'd recommend doing a complete re-install of Dokuwiki followed by only loading the NAVI plugin. Then monitor the navigation panel as you load more plugins. Ultimately, my problem was apparently linked to a plugin update issue... because everything worked fine after the re-install.

**Comment by atlarep** [comment]
Hi Randall, Thanks for your response. I checked the syntax and it looks fine, however, I just moved the missing pages into another namespace (B) and now they show in the navigation panel. It is really weird because I have other pages inside the first namespace (A) and they show properly. Not sure what to do but I will try your other suggestions.
